export const style = {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: { xs: "95%", sm: 400 },
    maxHeight: "90vh",
    bgcolor: "background.paper",
    border: "2px solid #000",
    boxShadow: 24,
    p: 3,
    display: "flex",
    flexDirection: { xs: "row", sm: "column" },
    alignItems: "center",
    justifyContent: "space-around",
    gap: 2,
    overflowY: "auto",
};
